[package]
name = "piff"
version = "0.1.0"
description = "Piff command-line PDF comparison tool"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[[bin]]
name = "piff"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
piff-core = { path = "../piff-core", version = "0.1.0" }
piff-semantic = { path = "../piff-semantic", version = "0.1.0" }
piff-pdfium = { path = "../piff-pdfium", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
